upstream_project_url: https://github.com/user-cont/conu

jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches: fedora-all
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
