dist_git_url: https://src.fedoraproject.org/rpms/conu.git
specfile_path: conu.spec
synced_files:
- conu.spec
upstream_package_name: conu
downstream_package_name: conu
jobs:
- job: sync_from_downstream
  trigger: commit
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: master
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: f31
- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: f30
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
# - job: tests
#   trigger: pull_request
#   metadata:
#     targets:
#     - fedora-30-x86_64
#     - fedora-31-x86_64
#     - fedora-rawhide-x86_64
