---
- name: Inastall dependencies needed for OpenShift
  hosts: all
  tasks:
  - name: Install rpms.
    yum:
      name:
      - git
      - docker
      state: present
  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive
  - name: Stop service firewall, if running
    systemd:
      name: firewalld
      state: stopped # firewall on CentOS does not allow docker login into OpenShift registry
  - name: Make sure docker is running
    systemd:
      name: docker
      state: started
  - name: Create directory for registry configuration
    file:
      path: /etc/docker/registry/
      state: directory
  - name: Create configuration for registry proxy
    copy:
      src: registry_config.yml
      dest: /etc/docker/registry/config.yml
      mode: 0644
  - name: Remove older container for registry mirror
    command: docker rm -f registry
    ignore_errors: yes
  - name: Run registry proxy
    command: >
      docker run -d -p 5000:5000 --restart=always
          --name registry
          -v /etc/docker/registry/config.yml:/etc/docker/registry/config.yml
          -v /var/lib/registry:/var/lib/registry:z
          docker.io/registry:2
  - name: Create docker deamon config
    file:
      path: /etc/docker/daemon.json
      state: touch
  - name: Add OpenShift insecure registry into docker deamon config
    copy:
      content: |
        {"insecure-registries" : [ "172.30.0.0/16" ],
         "registry-mirrors": ["http://localhost:5000"]}
      dest: /etc/docker/daemon.json
  - name: Restart docker because config has changed
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker
  - name: Install OpenShift server
    yum:
      name:
      - centos-release-openshift-origin311
      state: present
  - name: Install OpenShift client
    yum:
      name:
      - origin-clients
      state: present
  - name: Start Openshift cluster
    command: oc cluster up --base-dir=/var/tmp/openshift.local.clusterup --image='quay.io/openshift/origin-${component}:${version}'
    environment:
      PATH: "{{ ansible_env.PATH}}:/usr/local/bin"
      DOCKER_CONFIG: "/etc/docker/daemon.json"

  - name: Add permissions for developer account
    command: "{{ item }}"
    with_items:
      - oc login -u system:admin
      - oc adm policy add-cluster-role-to-user admin developer
      - oc adm policy add-cluster-role-to-user cluster-admin developer
      - oc login -u developer -p developer
